config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.save

    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :url, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gtex</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Building things for the web</h1>
<h2><%= link_to "Projects", projects_path%></h2>

app/views/projects/index.html.erb
<h1><a href="https://api.whatsapp.com/send?phone=5511984320432">Contact</a></h1>
<h1><a href="https://www.linkedin.com/in/guilherme-teixeira-b3074926">Linkedin</a></h1>
<div class="container-card" %>
  <% @projects.each do |project| %>
    <div class="card-product">
        <%= cl_image_tag project.photo.key, height: 300, width: 400, crop: :fill %>
        <div class="card-product-infos">
          <h2><%= project.name %> - <a href=<%= project.url %>>Visit</a></h2>
            <%= turbo_frame_tag id="techs" do %>
              <%= link_to project_path(project) do %>
                <h2>Techs:<i class="fa-solid fa-desktop fa-bounce"></i></h2>
              <% end%>
            <% end %>
        </div>
    </div>
  <% end %>
</div>

app/views/projects/new.html.erb
<%= form_with model: @project do |f| %>
	<%= f.text_field :name %>
	<%= f.text_field :desription %>
	<%= f.text_field :url %>
	<%= f.file_field :photo %>
	<%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<%= turbo_frame_tag id="techs" do%>
  <%= @project.description %>
<% end %>